import { _electron as electron } from 'playwright';
import os from 'node:os';
import { join } from 'node:path';
const app = await electron.launch({ args: [process.cwd(),'--no-sandbox',`--user-data-dir=${join(os.tmpdir(),'cwm-dom-'+Date.now())}`] });
const page = await app.firstWindow();
await page.waitForSelector('#application:not([hidden])', { timeout: 20000 });
await page.waitForTimeout(1500);
console.log('liens du rail :', await page.$$eval('.rail__lien', els => els.map(e => e.textContent.trim()).join(' | ')));
console.log('rail__pied    :', await page.$$eval('.rail__pied', els => els.map(e => `enfants=${e.children.length}`).join(',')) || 'ABSENT');
console.log('hauteur rail  :', await page.$eval('.rail', e => `${e.scrollHeight}px (visible ${e.clientHeight}px)`));
await app.close();
